#!/usr/bin/env node
/**
 * Renders the raster assets the web needs and SVG cannot cover: the 1200x630 social
 * card — one per published locale — the iOS home-screen icon, and a .ico for the contexts
 * that still ask for one.
 *
 * Why this is a separate script and not part of `gen-site`: it shells out to Chrome.
 * The gate has to run on any machine with Node and nothing else, and a build step that
 * needs a browser installed is a build step that fails for a contributor who has done
 * nothing wrong. So the outputs are committed as source assets and regenerated by hand
 * — run this after changing the mark, the palette, or the card's wording.
 *
 * The card is HTML rather than a hand-drawn image for the same reason the landing page
 * is generated: it fills the same {{tokens}} from the same derivation, so it cannot
 * claim a version or a repository the site does not. It also means the card translates
 * for free — one template, rendered once per entry in `gen-site.ts`'s PAGES, so adding a
 * locale there is the whole change and no card can be left behind in another language.
 *
 * Usage: node --experimental-strip-types scripts/gen-og.ts
 */
import { execFileSync } from 'child_process'
import { readFileSync, writeFileSync, mkdtempSync, rmSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { tmpdir } from 'os'
import { fileURLToPath } from 'url'
import { TOKENS, render, PAGES, localeTokens } from './gen-site.ts'
import { stripTemplateNote } from './lib/templates.ts'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SITE = join(ROOT, 'site')

const CHROME_CANDIDATES = [
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
  join(process.env.LOCALAPPDATA ?? '', 'Google/Chrome/Application/chrome.exe'),
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/usr/bin/google-chrome',
  '/usr/bin/chromium',
]

function findChrome(): string {
  const found = CHROME_CANDIDATES.find((p) => p && existsSync(p))
  if (!found) {
    throw new Error(
      'Chrome not found. This script rasterises with headless Chrome; install it, or ' +
        'leave the committed PNGs alone — nothing in `npm run check` depends on this script.'
    )
  }
  return found
}

/** Screenshot an HTML string at an exact pixel size. */
function shoot(chrome: string, html: string, width: number, height: number, out: string, transparent = false): void {
  const work = mkdtempSync(join(tmpdir(), 'sdk-og-'))
  try {
    const page = join(work, 'page.html')
    writeFileSync(page, html)
    execFileSync(
      chrome,
      [
        '--headless',
        '--disable-gpu',
        '--hide-scrollbars',
        '--force-device-scale-factor=1',
        ...(transparent ? ['--default-background-color=00000000'] : []),
        `--window-size=${width},${height}`,
        `--screenshot=${out}`,
        `file://${page.replace(/\\/g, '/')}`,
      ],
      { stdio: 'ignore' }
    )
  } finally {
    rmSync(work, { recursive: true, force: true })
  }
}

/**
 * An .ico wrapping a PNG. Every Windows version still in support reads PNG-encoded ICO
 * entries, so there is no need to emit a BMP: header, one directory entry, the PNG.
 * A width byte of 0 means 256 — irrelevant at 32px, but the reason the field is a byte.
 */
function icoFromPng(png: Buffer, size: number): Buffer {
  const dir = Buffer.alloc(22)
  dir.writeUInt16LE(0, 0) // reserved
  dir.writeUInt16LE(1, 2) // type: icon
  dir.writeUInt16LE(1, 4) // one image
  dir.writeUInt8(size === 256 ? 0 : size, 6)
  dir.writeUInt8(size === 256 ? 0 : size, 7)
  dir.writeUInt8(0, 8) // palette size: not paletted
  dir.writeUInt8(0, 9) // reserved
  dir.writeUInt16LE(1, 10) // colour planes
  dir.writeUInt16LE(32, 12) // bits per pixel
  dir.writeUInt32LE(png.length, 14)
  dir.writeUInt32LE(dir.length, 18) // image offset
  return Buffer.concat([dir, png])
}

const iconPage = (px: number, pad: number, background: string): string =>
  `<!doctype html><meta charset="utf-8"><style>
     html,body{margin:0;width:${px}px;height:${px}px;background:${background};
       display:flex;align-items:center;justify-content:center}
     svg{width:${px - pad * 2}px;height:${px - pad * 2}px;border-radius:${Math.round(px * 0.22)}px;display:block}
   </style>${TOKENS.mark}`

function main(): void {
  const chrome = findChrome()

  const cardTpl = stripTemplateNote(readFileSync(join(SITE, 'og.html'), 'utf8'))
  for (const page of PAGES) {
    shoot(chrome, render(cardTpl, localeTokens(page)), 1200, 630, join(SITE, page.ogImage))
  }

  // iOS draws its own rounded mask and never a transparent background, so this one is
  // rendered opaque on the mark's own clay rather than punched out.
  shoot(chrome, iconPage(180, 0, '#d97757'), 180, 180, join(SITE, 'apple-touch-icon.png'))

  const icoPng = join(SITE, 'favicon-32.png')
  shoot(chrome, iconPage(32, 0, '#d97757'), 32, 32, icoPng)
  writeFileSync(join(SITE, 'favicon.ico'), icoFromPng(readFileSync(icoPng), 32))
  rmSync(icoPng)

  for (const f of [...PAGES.map((p) => p.ogImage), 'apple-touch-icon.png', 'favicon.ico']) {
    console.log(`✓ site/${f} — ${readFileSync(join(SITE, f)).length} bytes`)
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main()
